### ISSUE TITLE
Changing skidmarks' color.

### ISSUE THREAD

**Issue by Nuklettin** [Nition/UnitySkidmarks#3]
Title explains itself. I have neon teal car tires and i want my skid marks to be same color, and if possible, with emission so it is always teal. Is it possible?

**Comment by Nition** [comment]
It wasn't possible, but I had actually added support for coloured skidmarks already in another project, so I've now ported it back here. Don't expect to get features added this easily all the time! But update to get the latest Skidmarks.cs, then call the new method variant:
`AddSkidMark(Vector3 pos, Vector3 normal, Color32 colour, int lastIndex)`

The colour's alpha will determine the skidmark's opacity in the same way "intensity" used to work.
